// SPDX-License-Identifier: GPL-3.0-or-later
// Created by Romain on 01/08/2020.

#ifndef AUTOCORRECT_LEVENSHTEIN_TYPES_H
#define AUTOCORRECT_LEVENSHTEIN_TYPES_H

#endif //AUTOCORRECT_LEVENSHTEIN_TYPES_H
